### PR TITLE
Add windows build to github workflow

### PR DESCRIPTION
**Pull request by planetmarshall**
Not sure if you're using github for CI but I've added this MSVC build config in case you find it useful.

### CODE REVIEW

**Comment by markcmiller86** [comment]
Presently, we're using Travis but I've wanted to move to GitHub actions...which is what this is, right?

**Comment by planetmarshall** [comment]
> Presently, we're using Travis but I've wanted to move to GitHub actions...which is what this is, right?

Yes, I use GitHub actions for all my open source projects. I find it useful to have everything in one place.

**Review by brtnfld — APPROVED** [review]
looks good to me. thanks!

**Comment by brtnfld** [comment]
Thanks, for updating, looks good.

**Pull request merged**
