### PR TITLE
Enable CMake testing

### PR DESCRIPTION
**Pull request by brtnfld**
Enable CMake testing:

- [ ] Convert Linux shell tests to Powershell to work on windows
- [x] Fix tests to build on windows
- [ ] Fix tests to pass on windows
- [ ] Enable github actions to run CMake tests on Linux
- [ ] Enable github actions to run CMake tests on Windows  
- [ ] Verify the CMake tests cover the same as Autotool's tests

### CODE REVIEW

**Comment by lrknox** [comment]
After setting HDF5_DIR and ZFP_DIR, creating a build subdirectory and running "CC=gcc FC=gfortran cmake -DCMAKE_INSTALL_PREFIX=/mnt/wrk/lrknox/h5z-zfp_install .." in the build directory (which succeeds), running either "make install" or running "cmake --build . --config Release" produced the following error:

[100%] Linking C executable print_h5repack_farg
/usr/bin/ld: CMakeFiles/test_write_plugin.dir/test_write.c.o: undefined reference to symbol 'exp@@GLIBC_2.2.5'
//usr/lib64/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [test/test_write_plugin] Error 1
gmake[1]: *** [test/CMakeFiles/test_write_plugin.dir/all] Error 2

**Comment by brtnfld** [comment]
Probably need to add ${CMAKE_DL_LIBS} to target_link_libraries()

**Comment by markcmiller86** [comment]
Ok, am returning my attention to this for a week. Where are we at with this? Is it still a work in progress?

**Comment by brtnfld** [comment]
Closing, replaced by PR #111

**Pull request closed without merging**
