### PR TITLE
Use ZFP_VERSION_PATCH if defined

### PR DESCRIPTION
**Pull request by markcmiller86**

### CODE REVIEW

**Comment by lindstro** [comment]
I would suggest simply using `ZFP_VERSION_STRING`, which already does what you want:

```
#define ZFP_VERSION_STRING \
  _zfp_str(ZFP_VERSION_MAJOR) "." \
  _zfp_str(ZFP_VERSION_MINOR) "." \
  _zfp_str(ZFP_VERSION_PATCH)
```

There are also new macros for generating version strings and numbers on develop that can be used as of the next release (see [include/zfp/version.h](https://github.com/LLNL/zfp/blob/develop/include/zfp/version.h)).  Those will be more reliable mechanisms going forward.

**Comment by jwsblokland** [comment]
Hello @markcmiller86 and @lindstro,

Would it be possible to finalize this pull request? 

The other day @lindstro made change to the develop branch of zfp in which the name of the variable ZFP_VERSION_RELEASE has been changed to ZFP_VERSION_DEVELOP (see version.h). As a result of this change I can no longer build the master branch of H5Z-ZFP against the latest version of the develop branch of zfp. Once this pull request is completed it will be possible again.

Best regards,
   Jan-Willem

**Review by brtnfld — APPROVED** [review]
lgtm

**Review by brtnfld — CHANGES_REQUESTED** [review]
Implement the changes suggested by  @lindstro.

**Comment by markcmiller86** [comment]
Yeah, so after I say @lindstro remark about using `ZFP_VERSION_STRING` from ZFP, I was kinda sorta expecting an update to this PR to use that instead. Then, it dropped of my radar.

That said, although ZFP appears to have implemented `ZFP_VERSION_STRING` quite a while ago it looks like its definition was moved from `include/zfp.h` to `include/zfp/version.h` only within the last year and I would like H5Z-ZFP to compile more widely than with *just* the current or most recent release of ZFP. `#include "zfp/version.h"` will fail for older versions. I think the logic should look something like...


```
#include "zfp.h"
#ifndef ZFP_VERSION_STRING
#include "zfp/version.h"
#endif
#define ZFP_VERSION_STR ZFP_VERSION_STRING
```

Thoughts?

**Comment by brtnfld** [comment]
But zfp/version.h is included zfp.h, so won't it still work?

**Comment by markcmiller86** [comment]
> But zfp/version.h is included zfp.h, so won't it still work?

Ah, I didn't investigate that far. If that is that is the case, then yes, it should work with old or new versions which means we can just replace the *definition* of `ZFP_VERSION_STR` with `ZFP_VERSION_STRING` effectively making the former an alias for the latter.

We could also wholly replace all instances of `ZFP_VERSION_STR` with `ZFP_VERSION_STRING` eliminating the need for the alias and that would be my preference.

**Comment by brtnfld** [comment]
Sound good to me. As soon as this is merged, I'll have a PR for GitHub actions to test with both develop and the latest tagged release versions of zfp.

**Comment by markcmiller86** [comment]
Supersceded by #80

**Pull request closed without merging**
